name: Build Docker
on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read version from file
        id: version
        run: |
          if [ -f VERSION ]; then
            VERSION=$(cat VERSION | tr -d '\n\r')
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            echo "Using version: $VERSION"
          else
            echo "VERSION file not found, using latest"
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push
        run: |
          # Build with version tag
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/comfyui:${{ steps.version.outputs.version }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/comfyui:${{ steps.version.outputs.version }}

          # Also tag and push as latest if this is a version (not 'latest')
          if [ "${{ steps.version.outputs.version }}" != "latest" ]; then
            docker tag ${{ secrets.DOCKERHUB_USERNAME }}/comfyui:${{ steps.version.outputs.version }} ${{ secrets.DOCKERHUB_USERNAME }}/comfyui:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/comfyui:latest
            echo "Pushed both ${{ steps.version.outputs.version }} and latest tags"
          fi
